### PR TITLE
Remove isotropic tensor function-approximated `exp`, `dexp`, `ln`

### LINKED ISSUE #4: Isotropic Tensor Functions
Add isotropic tensor functions like sqrt(T), exp(T), etc. [Source](https://www.google.at/url?sa=t&source=web&rct=j&url=https://classes.soe.ucsc.edu/cmps161/Winter14/papers/t4/RelatedWork/ItskovFourthOrder.pdf.pdf&ved=0ahUKEwjcnPfCjunXAhWEC-wKHfifBaAQFgg1MAM&usg=AOvVaw1Kx0_SJxhmPOpsZ9p_85AG)

Or Eigenvalue/Eigenvector Calculation with the help of LAPACK

### PR DESCRIPTION
**Pull request by adtzlr**
as these functions could be misleading - one could think `exp`, `dexp`, `ln` are analytic (exact) functions and not approximations.

Also cleanup the code (remove unused comments, internal variables and unused pages of the docs).

closes #4

### CODE REVIEW

**Comment by adtzlr** [comment]
@jfriedlein Do you agree with these changes? Many thanks in advance 😃

**Review by jfriedlein — COMMENTED** [review]
Changes are fine.

**Comment by jfriedlein** [comment]
I would further recommend two things:
- Add a link for instance in issue https://github.com/adtzlr/ttb/issues/4 to the former implementation, so if somebody needs a quick solution, they can directly find and use it.
- Maybe add an assertion to both functions in `libpower.f` that throws an error if the exponent is neither 0, -1, nor a positive integer. This should catch "pow_2(tensor,-2)". If somebody tries to be smart and calls `pow_2` with exponent 1/2 to get the square root, we still might get some problems. Even though `pow_2(tensor,0.5)` is caught by the compiler, `pow_2(stress,1/2)` is regarded as zero exponent. You have already explained what `Power` does in the documentation https://adtzlr.github.io/ttb/functions/power.html, but maybe you can add some further notes (`i`is integer) and protection (`i>=-1`).
If you agree, I can also do some of the changes myself and add a pull request.

**Comment by adtzlr** [comment]
> Changes are fine.

Many thanks!

**Comment by adtzlr** [comment]
> I would further recommend two things:
> 
> * Add a link for instance in issue [Isotropic Tensor Functions #4](https://github.com/adtzlr/ttb/issues/4) to the former implementation, so if somebody needs a quick solution, they can directly find and use it.
> * Maybe add an assertion to both functions in `libpower.f` that throws an error if the exponent is neither 0, -1, nor a positive integer. This should catch "pow_2(tensor,-2)". If somebody tries to be smart and calls `pow_2` with exponent 1/2 to get the square root, we still might get some problems. Even though `pow_2(tensor,0.5)` is caught by the compiler, `pow_2(stress,1/2)` is regarded as zero exponent. You have already explained what `Power` does in the documentation https://adtzlr.github.io/ttb/functions/power.html, but maybe you can add some further notes (`i`is integer) and protection (`i>=-1`).
>   If you agree, I can also do some of the changes myself and add a pull request.

I'll add a new issue for the enhancement of the power function.

**Pull request merged**
